<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyName>Privat2Ynab</AssemblyName>
    <Version>2.1.0</Version>
    <AssemblyVersion>2.1.0.0</AssemblyVersion>
    <FileVersion>2.1.0.0</FileVersion>
    <InformationalVersion>2.1.0</InformationalVersion>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>
      CA1515; <!-- Consider making public types internal -->
    </NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Privat2Ynab.Application\Privat2Ynab.Application.csproj" />
    <ProjectReference Include="..\Privat2Ynab.Infrastructure\Privat2Ynab.Infrastructure.csproj" />
  </ItemGroup>

</Project>