<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Flurl" />
    <PackageReference Include="Flurl.Http" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Privat2Ynab.Application\Privat2Ynab.Application.csproj" />
    <ProjectReference Include="..\Privat2Ynab.Domain\Privat2Ynab.Domain.csproj" />
  </ItemGroup>

</Project>